### ISSUE TITLE
Telegram bot support

### ISSUE THREAD

**Issue by mertaytore** [furkansahin/InvestmentMonitor#1]
Let's not pay 4.99$ and get notifications from a Telegram bot! 

@furkansahin can you assign me to this one? I think this might come in handy rather than a CLI application.

**Comment by furkansahin** [comment]
Well any contribution is welcome! 
Thnx for the idea 👍

**Comment by furkansahin** [comment]
I tried to integrate it with a telegram bot and initially got notifications but there are still many things to do. Reach me out for the key values and necessary imports ;)

**Comment by furkansahin** [comment]
maincurrency - Add the currency you live with
watchcurrency - Add the currency you want to watch
removecurrency - Remove the currency you're watching
sayhi - Interact with our poor bot
minthreshold - Your minimum threshold to be notified
maxthreshold - Your maximum threshold to be notified
addwatchcurrency - Add one more currency you are watching
changemaincurrency - Change the currency you live with

**Comment by furkansahin** [comment]
Telegram bot is done!
